on: [push]

env:
  CARGO_TERM_COLOR: always
  SQLX_VERSION: 0.8.0
  SQLX_FEATURES: "rustls,postgres"

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: newsletter
        ports:
          - 5433:5432
    steps:
      # Check out the repo onto the runner in order to run scripts/actions
      # against the code.
      - uses: actions/checkout@v4
      # Install a Rust toolchain using rustup. Caches intermediate build
      # artifacts.
      - name: Install rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Install sqlx-cli
        run: cargo install sqlx-cli
          --version=${{ env.SQLX_VERSION }}
          --features ${{ env.SQLX_FEATURES }}
          --no-default-features
          --locked
        # ^ `--locked` forces cargo to use the packaged `Cargo.lock` file
        # if available. This can ensure reproducible builds.

      - name: Migrate database
        run: |
          # v `SKIP_DOCKER` skips creating a postgres docker container
          SKIP_DOCKER=true ./scripts/init_db

      - name: Run tests
        run: cargo test

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
      - name: Enforce formatting
        run: cargo fmt --check

  lint:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: newsletter
        ports:
          - 5433:5432
    steps:
      - uses: actions/checkout@v4
      - name: Install rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy

      - name: Install sqlx-cli
        run: cargo install sqlx-cli
          --version=${{ env.SQLX_VERSION }}
          --features ${{ env.SQLX_FEATURES }}
          --no-default-features
          --locked
        # ^ `--locked` forces cargo to use the packaged `Cargo.lock` file
        # if available. This can ensure reproducible builds.

      - name: Migrate database
        run: |
          # v `SKIP_DOCKER` skips creating a postgres docker container
          SKIP_DOCKER=true ./scripts/init_db

      - name: Run linter
        run: cargo clippy -- -D warnings
